RedHat79:
  user: chg
  host: 192.168.3.53
  port: 22
  option:
    IdentityFile: ~/.ssh/id_ed25519
    BatchMode: yes
    # StrictHostKeyChecking: yes
    # Compression: no
  log: ./logs/ScpExecutor.log
