task1: # 上傳複數檔案到遠端資料夾
  mode: put
  local: |-
    local_dir1/File1.txt
    local_dir2/File2.txt
  remote:
    ~/remote_dir/

task2: # 下載複數檔案到本地資料夾
  mode: get
  local:
    local_dir/
  remote: |-
    ~/remote_dir1/File1.txt
    ~/remote_dir2/File2.txt

task3: # 1對1下載
  mode: get
  local: |-
    local_dir1/File1.txt
    local_dir2/File2.txt
  remote: |-
    ~/remote_dir1/File1.txt
    ~/remote_dir2/File2.txt

task4: # 1對1上傳
  mode: put
  local: |-
    local_dir1/File1.txt
    local_dir2/File2.txt
  remote: |-
    ~/remote_dir1/File1.txt
    ~/remote_dir2/File2.txt

task5: # 遞歸上傳資料夾
  option: -rp
  mode: put
  local:
    local_dir/*
  remote:
    ~/remote_dir/

task6: # 遞歸下載資料夾
  option: -rp
  mode: get
  local:
    local_dir/
  remote:
    ~/remote_dir/*

task7: # 遠端複製到遠端
  mode: put
  local:
    ~/TestFile.txt
  remote:
    ~/TestFile.txt
